source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zucred/Specs.git'

use_frameworks!

pod "VMPayment", :path => '../../VMPayment’

pod 'VMLogger'
pod 'Stripe'
pod 'PayPal-iOS-SDK'
pod 'BraintreeDropIn'

target 'VMPaymentExample' do

end

target 'VMPaymentTests' do
  pod "VMPayment", :path => '../../VMPayment'
end

target 'VMPaymentUITests' do
  pod "VMPayment", :path => '../../VMPayment'
end
